#!/bin/bash
cd /root/pblog/content/post
mkdir $1
cd $1
echo "---" >> index.md
echo "author: Joker" >> index.md
echo "title: " >> index.md
echo "slug: $1" >> index.md
echo "date: `date "+%Y-%m-%d"`T`date "+%H:%m:%S"`+08:00" >> index.md
echo "description: " >> index.md
echo "image: " >> index.md
echo "categories: []" >> index.md
echo "tags: []" >> index.md
echo "---" >> index.md
